app = "aerocast-jakarta"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app = "/app/.venv/bin/gunicorn --bind 0.0.0.0:8080 backend:app"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
